#+TITLE: [WIP] Learning new programming language

* Introduction

Learning a new programming language is not always easy. For me, the
most difficult part is to find something that I would like to build
along the process.

It is difficult to find such projects because there are two major
contradicting requirements: first, they should not be so big so that
you give up, second, they should not be so trivial so that you don't
explore the language features well. I think the imbalance of these two
requirements leads to interruptions in the learning process.

I want to make a collection of project ideas that I would like to work
on whenever I want to try out a new language.

** TODO maybe try to steal some ideas from https://github.com/seven1m/30-days-of-elixir

* Projects

** Fundamentals

These tasks are supposed to make me comfortable with the basic data
structure, control flow, syntax et cetera of the language. They are
supposed to be trivial in nature and should not take too long to
accomplish.

*** URL Spy

Write a command line application that takes a list of URL, fetches
them and provides meta information such as hostname, IP,
request/response time, opengraph information et cetera.

*** URL Downloader

Write a command line app that accepts a list of URL, downloads and
saves them as per the content type of the response.

**** [[https://github.com/poudel/go-save-url][go-save-url]]

This was supposed to make me a bit more familiar with the Go syntax
and the std library. I've attempted to do Go before but I needed a
refresher.

*** Write a simple shell

Is supposed to teach me how to work with user input.

**** [[https://github.com/poudel/go-toy-shell][Go toy shell]]

I learned how to take input from the user.

** Exploring the world

These are supposed to allow me to use language tools, libraries et
cetera to interact with the real world. Things that require network,
disk, and/or database access should fall into this section.

*** Simple static site generator

Write a simple static site generator. You can port
[[https://github.com/poudel/harmonique]].

**** [[https://github.com/poudel/go-static-sites][Go static sites]]

I learned a bit more about the way ~io~ is done in Go. I also learned
how to use external libraries. I'm still getting used to the way error
handling is done in the Go land. I played around with structs. I want
to learn how to write tests.

*** Partial httpbin.org clone

Write a clone of [[https://httpbin.org]] with a subset of the actual APIs
if not everything. It is supposed to teach me how to write a
trivial http server in that language.

** Applied

Some languages are general purpose. Some are suited for certain type
of tasks. I believe that we should always strive to use the best tool
possible for the given task.

The tasks in this system are supposed to teach me how to build
full-fledged application using the language. The tasks can vary across
the language. If the language is popular for web developments, the
task should be to build web applications and so on.

In short, this section should allow me to apply the skills from
previous sections to create something.

1. Port [[http://norvig.com/lispy.html][lispy]], the educational lisp interpreter by Peter Norvig.
2. Write a simple database copy application that accepts credentials
   for source and target database, and the name of table that needs to
   be migrated to the target database.
